// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.2.5.0
// Machine:  MSI
// DateTime: 5/13/2026 1:07:00 PM
// Input file <MiniLang.y - 5/13/2026 1:06:50 PM>

// options: lines gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using StarodubOleg.GPPG.Runtime;

namespace Proyecto1Analizador
{
public enum Tokens {error=2,EOF=3,PRINT=4,PRFLOAT=5,PRCHAR=6,
    PRBOOL=7,PRIF=8,PRELIF=9,PRELSE=10,PRWHILE=11,PRDEF=12,
    PRRETURN=13,PRREAD=14,PRWRITE=15,INT=16,FLOAT=17,CHAR=18,
    BOOL=19,ID=20,OR=21,AND=22,NOT=23,SUM=24,
    RESTA=25,MULTI=26,DIV=27,PORCENTAJE=28,IGUAL=29,IGUALIGUAL=30,
    NOIGUAL=31,MAYORQ=32,MENORQ=33,MAYORIGUAL=34,MENORIGUAL=35,PARENI=36,
    PAREND=37,COMA=38,NEWLINE=39,INDENT=40,DEDENT=41,ERROR=42,
    UMINUS=43};

// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.2.5.0")]
public abstract class ScanBase : AbstractScanner<int,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.2.5.0")]
public class ScanObj {
  public int token;
  public int yylval;
  public LexLocation yylloc;
  public ScanObj( int t, int val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.2.5.0")]
public partial class Parser: ShiftReduceParser<int, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[106];
  private static State[] states = new State[175];
  private static string[] nonTerms = new string[] {
      "S", "$accept", "LINEAS", "LINEA", "SENTENCIA_SIMPLE", "ENCABEZADO_CONTROL", 
      "FUNCION", "RETURN", "DECLARACION", "ASIGNACION", "ENTRADASALIDA", "LLAMADA", 
      "IF_SIMPLE", "ELSE_SIMPLE", "WHILE_SIMPLE", "TIPO", "DATO", "EXPRESION", 
      "CONDICION", "PARAMETROS", "BLOQUEFUNCION", "PARAMS", "PARAM", "LINEASFUNCION", 
      "LINEAFUNCION", "ARGUMENTOS", "LISTAARGUMENTOS", };

  static Parser() {
    states[0] = new State(-4,new int[]{-1,1,-3,3});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{4,66,5,67,6,68,7,69,20,71,14,76,15,85,8,97,10,108,11,110,12,119,13,136,40,168,41,169,39,170,42,171,2,173,3,-2},new int[]{-4,4,-5,5,-9,7,-16,8,-10,70,-11,75,-12,93,-6,94,-13,96,-14,107,-15,109,-7,118,-8,166});
    states[4] = new State(-3);
    states[5] = new State(new int[]{39,6});
    states[6] = new State(-5);
    states[7] = new State(-14);
    states[8] = new State(new int[]{20,9,2,65});
    states[9] = new State(new int[]{29,10,39,-29});
    states[10] = new State(new int[]{2,64,23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,11,-12,48,-17,58});
    states[11] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-30});
    states[12] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,13,-12,48,-17,58});
    states[13] = new State(new int[]{21,-85,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-85,37,-85,2,-85,38,-85});
    states[14] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,15,-12,48,-17,58});
    states[15] = new State(new int[]{21,-86,22,-86,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-86,37,-86,2,-86,38,-86});
    states[16] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,17,-12,48,-17,58});
    states[17] = new State(new int[]{21,-87,22,-87,38,-87,2,-87,37,-87,39,-87,24,28,25,30,26,32,27,34,28,36});
    states[18] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,19,-12,48,-17,58});
    states[19] = new State(new int[]{21,-88,22,-88,38,-88,2,-88,37,-88,39,-88,24,28,25,30,26,32,27,34,28,36});
    states[20] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,21,-12,48,-17,58});
    states[21] = new State(new int[]{21,-89,22,-89,38,-89,2,-89,37,-89,39,-89,24,28,25,30,26,32,27,34,28,36});
    states[22] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,23,-12,48,-17,58});
    states[23] = new State(new int[]{21,-90,22,-90,38,-90,2,-90,37,-90,39,-90,24,28,25,30,26,32,27,34,28,36});
    states[24] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,25,-12,48,-17,58});
    states[25] = new State(new int[]{21,-91,22,-91,38,-91,2,-91,37,-91,39,-91,24,28,25,30,26,32,27,34,28,36});
    states[26] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,27,-12,48,-17,58});
    states[27] = new State(new int[]{21,-92,22,-92,38,-92,2,-92,37,-92,39,-92,24,28,25,30,26,32,27,34,28,36});
    states[28] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,29,-12,48,-17,58});
    states[29] = new State(new int[]{21,-93,22,-93,30,-93,31,-93,32,-93,33,-93,34,-93,35,-93,24,-93,25,-93,26,32,27,34,28,36,39,-93,37,-93,2,-93,38,-93});
    states[30] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,31,-12,48,-17,58});
    states[31] = new State(new int[]{21,-94,22,-94,30,-94,31,-94,32,-94,33,-94,34,-94,35,-94,24,-94,25,-94,26,32,27,34,28,36,39,-94,37,-94,2,-94,38,-94});
    states[32] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,33,-12,48,-17,58});
    states[33] = new State(-95);
    states[34] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,35,-12,48,-17,58});
    states[35] = new State(-96);
    states[36] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,37,-12,48,-17,58});
    states[37] = new State(-97);
    states[38] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,39,-12,48,-17,58});
    states[39] = new State(new int[]{21,-98,22,-98,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-98,37,-98,2,-98,38,-98});
    states[40] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,41,-12,48,-17,58});
    states[41] = new State(-99);
    states[42] = new State(new int[]{2,46,23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,43,-12,48,-17,58});
    states[43] = new State(new int[]{37,44,2,45,21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36});
    states[44] = new State(-100);
    states[45] = new State(-101);
    states[46] = new State(new int[]{37,47});
    states[47] = new State(-102);
    states[48] = new State(-103);
    states[49] = new State(new int[]{36,50,21,-104,22,-104,30,-104,31,-104,32,-104,33,-104,34,-104,35,-104,24,-104,25,-104,26,-104,27,-104,28,-104,39,-104,37,-104,2,-104,38,-104});
    states[50] = new State(new int[]{23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62,37,-80,2,-80},new int[]{-26,51,-27,54,-18,63,-12,48,-17,58});
    states[51] = new State(new int[]{37,52,2,53});
    states[52] = new State(-77);
    states[53] = new State(-78);
    states[54] = new State(new int[]{38,55,37,-79,2,-79});
    states[55] = new State(new int[]{2,57,23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,56,-12,48,-17,58});
    states[56] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,38,-82,37,-82,2,-82});
    states[57] = new State(-83);
    states[58] = new State(-105);
    states[59] = new State(-25);
    states[60] = new State(-26);
    states[61] = new State(-27);
    states[62] = new State(-28);
    states[63] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,38,-81,37,-81,2,-81});
    states[64] = new State(-32);
    states[65] = new State(-31);
    states[66] = new State(-21);
    states[67] = new State(-22);
    states[68] = new State(-23);
    states[69] = new State(-24);
    states[70] = new State(-15);
    states[71] = new State(new int[]{29,72,36,50});
    states[72] = new State(new int[]{2,74,23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,73,-12,48,-17,58});
    states[73] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-33});
    states[74] = new State(-34);
    states[75] = new State(-16);
    states[76] = new State(new int[]{36,77,20,83});
    states[77] = new State(new int[]{20,78,23,38,25,40,36,42,16,59,17,60,18,61,19,62},new int[]{-18,81,-12,48,-17,58});
    states[78] = new State(new int[]{37,79,2,80,36,50,21,-104,22,-104,30,-104,31,-104,32,-104,33,-104,34,-104,35,-104,24,-104,25,-104,26,-104,27,-104,28,-104});
    states[79] = new State(-69);
    states[80] = new State(-73);
    states[81] = new State(new int[]{37,82,21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36});
    states[82] = new State(-71);
    states[83] = new State(new int[]{37,84});
    states[84] = new State(-72);
    states[85] = new State(new int[]{36,86,23,38,25,40,20,49,16,59,17,60,18,61,19,62},new int[]{-18,91,-12,48,-17,58});
    states[86] = new State(new int[]{37,90,2,46,23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,87,-12,48,-17,58});
    states[87] = new State(new int[]{37,88,2,89,21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36});
    states[88] = new State(new int[]{39,-70,37,-100,21,-100,22,-100,30,-100,31,-100,32,-100,33,-100,34,-100,35,-100,24,-100,25,-100,26,-100,27,-100,28,-100});
    states[89] = new State(new int[]{39,-76,37,-101,21,-101,22,-101,30,-101,31,-101,32,-101,33,-101,34,-101,35,-101,24,-101,25,-101,26,-101,27,-101,28,-101});
    states[90] = new State(-74);
    states[91] = new State(new int[]{37,92,21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36});
    states[92] = new State(-75);
    states[93] = new State(-17);
    states[94] = new State(new int[]{39,95});
    states[95] = new State(-6);
    states[96] = new State(-18);
    states[97] = new State(new int[]{36,98,23,38,25,40,20,49,16,59,17,60,18,61,19,62},new int[]{-19,104,-18,106,-12,48,-17,58});
    states[98] = new State(new int[]{2,101,23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-19,99,-18,103,-12,48,-17,58});
    states[99] = new State(new int[]{37,100,39,-37});
    states[100] = new State(-35);
    states[101] = new State(new int[]{37,102});
    states[102] = new State(new int[]{39,-38,21,-102,22,-102,30,-102,31,-102,32,-102,33,-102,34,-102,35,-102,24,-102,25,-102,26,-102,27,-102,28,-102,37,-102});
    states[103] = new State(new int[]{37,44,2,45,21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-84});
    states[104] = new State(new int[]{37,105});
    states[105] = new State(-36);
    states[106] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,37,-84});
    states[107] = new State(-19);
    states[108] = new State(-39);
    states[109] = new State(-20);
    states[110] = new State(new int[]{36,111,23,38,25,40,20,49,16,59,17,60,18,61,19,62},new int[]{-19,116,-18,106,-12,48,-17,58});
    states[111] = new State(new int[]{2,114,23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-19,112,-18,103,-12,48,-17,58});
    states[112] = new State(new int[]{37,113,39,-42});
    states[113] = new State(-40);
    states[114] = new State(new int[]{37,115});
    states[115] = new State(new int[]{39,-43,21,-102,22,-102,30,-102,31,-102,32,-102,33,-102,34,-102,35,-102,24,-102,25,-102,26,-102,27,-102,28,-102,37,-102});
    states[116] = new State(new int[]{37,117});
    states[117] = new State(-41);
    states[118] = new State(-7);
    states[119] = new State(new int[]{20,120,36,161});
    states[120] = new State(new int[]{36,121,4,66,5,67,6,68,7,69,37,-49},new int[]{-20,157,-22,149,-23,156,-16,153});
    states[121] = new State(new int[]{4,66,5,67,6,68,7,69,37,-49,39,-49},new int[]{-20,122,-22,149,-23,156,-16,153});
    states[122] = new State(new int[]{37,123,39,147});
    states[123] = new State(new int[]{39,124});
    states[124] = new State(new int[]{40,126},new int[]{-21,125});
    states[125] = new State(-44);
    states[126] = new State(new int[]{41,145,4,66,5,67,6,68,7,69,20,71,14,76,15,85,8,97,10,108,11,110,13,136,40,139,39,140,42,141,2,143},new int[]{-24,127,-25,146,-5,130,-9,7,-16,8,-10,70,-11,75,-12,93,-6,132,-13,96,-14,107,-15,109,-8,134});
    states[127] = new State(new int[]{41,128,4,66,5,67,6,68,7,69,20,71,14,76,15,85,8,97,10,108,11,110,13,136,40,139,39,140,42,141,2,143},new int[]{-25,129,-5,130,-9,7,-16,8,-10,70,-11,75,-12,93,-6,132,-13,96,-14,107,-15,109,-8,134});
    states[128] = new State(-57);
    states[129] = new State(-59);
    states[130] = new State(new int[]{39,131});
    states[131] = new State(-61);
    states[132] = new State(new int[]{39,133});
    states[133] = new State(-62);
    states[134] = new State(new int[]{39,135});
    states[135] = new State(-63);
    states[136] = new State(new int[]{2,138,23,38,25,40,36,42,20,49,16,59,17,60,18,61,19,62},new int[]{-18,137,-12,48,-17,58});
    states[137] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-55});
    states[138] = new State(-56);
    states[139] = new State(-64);
    states[140] = new State(-66);
    states[141] = new State(new int[]{39,142});
    states[142] = new State(-67);
    states[143] = new State(new int[]{39,144});
    states[144] = new State(-68);
    states[145] = new State(-58);
    states[146] = new State(-60);
    states[147] = new State(new int[]{40,126},new int[]{-21,148});
    states[148] = new State(-47);
    states[149] = new State(new int[]{38,150,37,-48,39,-48});
    states[150] = new State(new int[]{2,152,4,66,5,67,6,68,7,69},new int[]{-23,151,-16,153});
    states[151] = new State(-51);
    states[152] = new State(-52);
    states[153] = new State(new int[]{20,154,2,155});
    states[154] = new State(-53);
    states[155] = new State(-54);
    states[156] = new State(-50);
    states[157] = new State(new int[]{37,158});
    states[158] = new State(new int[]{39,159});
    states[159] = new State(new int[]{40,126},new int[]{-21,160});
    states[160] = new State(-46);
    states[161] = new State(new int[]{4,66,5,67,6,68,7,69,37,-49},new int[]{-20,162,-22,149,-23,156,-16,153});
    states[162] = new State(new int[]{37,163});
    states[163] = new State(new int[]{39,164});
    states[164] = new State(new int[]{40,126},new int[]{-21,165});
    states[165] = new State(-45);
    states[166] = new State(new int[]{39,167});
    states[167] = new State(-8);
    states[168] = new State(-9);
    states[169] = new State(-10);
    states[170] = new State(-11);
    states[171] = new State(new int[]{39,172});
    states[172] = new State(-12);
    states[173] = new State(new int[]{39,174});
    states[174] = new State(-13);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,3});
    rules[2] = new Rule(-1, new int[]{-3});
    rules[3] = new Rule(-3, new int[]{-3,-4});
    rules[4] = new Rule(-3, new int[]{});
    rules[5] = new Rule(-4, new int[]{-5,39});
    rules[6] = new Rule(-4, new int[]{-6,39});
    rules[7] = new Rule(-4, new int[]{-7});
    rules[8] = new Rule(-4, new int[]{-8,39});
    rules[9] = new Rule(-4, new int[]{40});
    rules[10] = new Rule(-4, new int[]{41});
    rules[11] = new Rule(-4, new int[]{39});
    rules[12] = new Rule(-4, new int[]{42,39});
    rules[13] = new Rule(-4, new int[]{2,39});
    rules[14] = new Rule(-5, new int[]{-9});
    rules[15] = new Rule(-5, new int[]{-10});
    rules[16] = new Rule(-5, new int[]{-11});
    rules[17] = new Rule(-5, new int[]{-12});
    rules[18] = new Rule(-6, new int[]{-13});
    rules[19] = new Rule(-6, new int[]{-14});
    rules[20] = new Rule(-6, new int[]{-15});
    rules[21] = new Rule(-16, new int[]{4});
    rules[22] = new Rule(-16, new int[]{5});
    rules[23] = new Rule(-16, new int[]{6});
    rules[24] = new Rule(-16, new int[]{7});
    rules[25] = new Rule(-17, new int[]{16});
    rules[26] = new Rule(-17, new int[]{17});
    rules[27] = new Rule(-17, new int[]{18});
    rules[28] = new Rule(-17, new int[]{19});
    rules[29] = new Rule(-9, new int[]{-16,20});
    rules[30] = new Rule(-9, new int[]{-16,20,29,-18});
    rules[31] = new Rule(-9, new int[]{-16,2});
    rules[32] = new Rule(-9, new int[]{-16,20,29,2});
    rules[33] = new Rule(-10, new int[]{20,29,-18});
    rules[34] = new Rule(-10, new int[]{20,29,2});
    rules[35] = new Rule(-13, new int[]{8,36,-19,37});
    rules[36] = new Rule(-13, new int[]{8,-19,37});
    rules[37] = new Rule(-13, new int[]{8,36,-19});
    rules[38] = new Rule(-13, new int[]{8,36,2,37});
    rules[39] = new Rule(-14, new int[]{10});
    rules[40] = new Rule(-15, new int[]{11,36,-19,37});
    rules[41] = new Rule(-15, new int[]{11,-19,37});
    rules[42] = new Rule(-15, new int[]{11,36,-19});
    rules[43] = new Rule(-15, new int[]{11,36,2,37});
    rules[44] = new Rule(-7, new int[]{12,20,36,-20,37,39,-21});
    rules[45] = new Rule(-7, new int[]{12,36,-20,37,39,-21});
    rules[46] = new Rule(-7, new int[]{12,20,-20,37,39,-21});
    rules[47] = new Rule(-7, new int[]{12,20,36,-20,39,-21});
    rules[48] = new Rule(-20, new int[]{-22});
    rules[49] = new Rule(-20, new int[]{});
    rules[50] = new Rule(-22, new int[]{-23});
    rules[51] = new Rule(-22, new int[]{-22,38,-23});
    rules[52] = new Rule(-22, new int[]{-22,38,2});
    rules[53] = new Rule(-23, new int[]{-16,20});
    rules[54] = new Rule(-23, new int[]{-16,2});
    rules[55] = new Rule(-8, new int[]{13,-18});
    rules[56] = new Rule(-8, new int[]{13,2});
    rules[57] = new Rule(-21, new int[]{40,-24,41});
    rules[58] = new Rule(-21, new int[]{40,41});
    rules[59] = new Rule(-24, new int[]{-24,-25});
    rules[60] = new Rule(-24, new int[]{-25});
    rules[61] = new Rule(-25, new int[]{-5,39});
    rules[62] = new Rule(-25, new int[]{-6,39});
    rules[63] = new Rule(-25, new int[]{-8,39});
    rules[64] = new Rule(-25, new int[]{40});
    rules[65] = new Rule(-25, new int[]{41});
    rules[66] = new Rule(-25, new int[]{39});
    rules[67] = new Rule(-25, new int[]{42,39});
    rules[68] = new Rule(-25, new int[]{2,39});
    rules[69] = new Rule(-11, new int[]{14,36,20,37});
    rules[70] = new Rule(-11, new int[]{15,36,-18,37});
    rules[71] = new Rule(-11, new int[]{14,36,-18,37});
    rules[72] = new Rule(-11, new int[]{14,20,37});
    rules[73] = new Rule(-11, new int[]{14,36,20,2});
    rules[74] = new Rule(-11, new int[]{15,36,37});
    rules[75] = new Rule(-11, new int[]{15,-18,37});
    rules[76] = new Rule(-11, new int[]{15,36,-18,2});
    rules[77] = new Rule(-12, new int[]{20,36,-26,37});
    rules[78] = new Rule(-12, new int[]{20,36,-26,2});
    rules[79] = new Rule(-26, new int[]{-27});
    rules[80] = new Rule(-26, new int[]{});
    rules[81] = new Rule(-27, new int[]{-18});
    rules[82] = new Rule(-27, new int[]{-27,38,-18});
    rules[83] = new Rule(-27, new int[]{-27,38,2});
    rules[84] = new Rule(-19, new int[]{-18});
    rules[85] = new Rule(-18, new int[]{-18,21,-18});
    rules[86] = new Rule(-18, new int[]{-18,22,-18});
    rules[87] = new Rule(-18, new int[]{-18,30,-18});
    rules[88] = new Rule(-18, new int[]{-18,31,-18});
    rules[89] = new Rule(-18, new int[]{-18,32,-18});
    rules[90] = new Rule(-18, new int[]{-18,33,-18});
    rules[91] = new Rule(-18, new int[]{-18,34,-18});
    rules[92] = new Rule(-18, new int[]{-18,35,-18});
    rules[93] = new Rule(-18, new int[]{-18,24,-18});
    rules[94] = new Rule(-18, new int[]{-18,25,-18});
    rules[95] = new Rule(-18, new int[]{-18,26,-18});
    rules[96] = new Rule(-18, new int[]{-18,27,-18});
    rules[97] = new Rule(-18, new int[]{-18,28,-18});
    rules[98] = new Rule(-18, new int[]{23,-18});
    rules[99] = new Rule(-18, new int[]{25,-18});
    rules[100] = new Rule(-18, new int[]{36,-18,37});
    rules[101] = new Rule(-18, new int[]{36,-18,2});
    rules[102] = new Rule(-18, new int[]{36,2,37});
    rules[103] = new Rule(-18, new int[]{-12});
    rules[104] = new Rule(-18, new int[]{20});
    rules[105] = new Rule(-18, new int[]{-17});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 12: // LINEA -> ERROR, NEWLINE
#line 44 "MiniLang.y"
                    { yyerror("token lexico invalido dentro de la sentencia"); }
#line default
        break;
      case 13: // LINEA -> error, NEWLINE
#line 45 "MiniLang.y"
                    { yyerror("sentencia no valida o incompleta"); }
#line default
        break;
      case 31: // DECLARACION -> TIPO, error
#line 78 "MiniLang.y"
                 { yyerror("despues del tipo se esperaba un identificador"); }
#line default
        break;
      case 32: // DECLARACION -> TIPO, ID, IGUAL, error
#line 79 "MiniLang.y"
                          { yyerror("despues de '=' se esperaba una expresion valida"); }
#line default
        break;
      case 34: // ASIGNACION -> ID, IGUAL, error
#line 84 "MiniLang.y"
                     { yyerror("despues de '=' se esperaba una expresion valida"); }
#line default
        break;
      case 36: // IF_SIMPLE -> PRIF, CONDICION, PAREND
#line 89 "MiniLang.y"
                            { yyerror("en if falta el parentesis de apertura '('"); }
#line default
        break;
      case 37: // IF_SIMPLE -> PRIF, PARENI, CONDICION
#line 90 "MiniLang.y"
                            { yyerror("en if falta el parentesis de cierre ')'"); }
#line default
        break;
      case 38: // IF_SIMPLE -> PRIF, PARENI, error, PAREND
#line 91 "MiniLang.y"
                               { yyerror("la condicion del if no es valida"); }
#line default
        break;
      case 41: // WHILE_SIMPLE -> PRWHILE, CONDICION, PAREND
#line 100 "MiniLang.y"
                               { yyerror("en while falta el parentesis de apertura '('"); }
#line default
        break;
      case 42: // WHILE_SIMPLE -> PRWHILE, PARENI, CONDICION
#line 101 "MiniLang.y"
                               { yyerror("en while falta el parentesis de cierre ')'"); }
#line default
        break;
      case 43: // WHILE_SIMPLE -> PRWHILE, PARENI, error, PAREND
#line 102 "MiniLang.y"
                                  { yyerror("la condicion del while no es valida"); }
#line default
        break;
      case 45: // FUNCION -> PRDEF, PARENI, PARAMETROS, PAREND, NEWLINE, BLOQUEFUNCION
#line 107 "MiniLang.y"
                                                           { yyerror("despues de def se esperaba el nombre de la funcion"); }
#line default
        break;
      case 46: // FUNCION -> PRDEF, ID, PARAMETROS, PAREND, NEWLINE, BLOQUEFUNCION
#line 108 "MiniLang.y"
                                                       { yyerror("en la funcion falta el parentesis de apertura '('"); }
#line default
        break;
      case 47: // FUNCION -> PRDEF, ID, PARENI, PARAMETROS, NEWLINE, BLOQUEFUNCION
#line 109 "MiniLang.y"
                                                       { yyerror("en la funcion falta el parentesis de cierre ')'"); }
#line default
        break;
      case 52: // PARAMS -> PARAMS, COMA, error
#line 120 "MiniLang.y"
                        { yyerror("despues de la coma se esperaba otro parametro"); }
#line default
        break;
      case 54: // PARAM -> TIPO, error
#line 125 "MiniLang.y"
                 { yyerror("en el parametro falta el identificador"); }
#line default
        break;
      case 56: // RETURN -> PRRETURN, error
#line 130 "MiniLang.y"
                     { yyerror("return necesita una expresion valida"); }
#line default
        break;
      case 58: // BLOQUEFUNCION -> INDENT, DEDENT
#line 135 "MiniLang.y"
                    { yyerror("el bloque de la funcion no puede estar vacio"); }
#line default
        break;
      case 67: // LINEAFUNCION -> ERROR, NEWLINE
#line 150 "MiniLang.y"
                    { yyerror("token lexico invalido dentro de la funcion"); }
#line default
        break;
      case 68: // LINEAFUNCION -> error, NEWLINE
#line 151 "MiniLang.y"
                    { yyerror("sentencia no valida dentro de la funcion"); }
#line default
        break;
      case 71: // ENTRADASALIDA -> PRREAD, PARENI, EXPRESION, PAREND
#line 157 "MiniLang.y"
                                     { yyerror("Read solo puede recibir un identificador"); }
#line default
        break;
      case 72: // ENTRADASALIDA -> PRREAD, ID, PAREND
#line 158 "MiniLang.y"
                       { yyerror("en Read falta el parentesis de apertura '('"); }
#line default
        break;
      case 73: // ENTRADASALIDA -> PRREAD, PARENI, ID, error
#line 159 "MiniLang.y"
                             { yyerror("en Read falta el parentesis de cierre ')'"); }
#line default
        break;
      case 74: // ENTRADASALIDA -> PRWRITE, PARENI, PAREND
#line 160 "MiniLang.y"
                            { yyerror("Write necesita una expresion valida"); }
#line default
        break;
      case 75: // ENTRADASALIDA -> PRWRITE, EXPRESION, PAREND
#line 161 "MiniLang.y"
                               { yyerror("en Write falta el parentesis de apertura '('"); }
#line default
        break;
      case 76: // ENTRADASALIDA -> PRWRITE, PARENI, EXPRESION, error
#line 162 "MiniLang.y"
                                     { yyerror("en Write falta el parentesis de cierre ')'"); }
#line default
        break;
      case 78: // LLAMADA -> ID, PARENI, ARGUMENTOS, error
#line 167 "MiniLang.y"
                                 { yyerror("en la llamada falta el parentesis de cierre ')'"); }
#line default
        break;
      case 83: // LISTAARGUMENTOS -> LISTAARGUMENTOS, COMA, error
#line 178 "MiniLang.y"
                                 { yyerror("despues de la coma se esperaba otro argumento"); }
#line default
        break;
      case 101: // EXPRESION -> PARENI, EXPRESION, error
#line 202 "MiniLang.y"
                             { yyerror("en la expresion falta el parentesis de cierre ')'"); }
#line default
        break;
      case 102: // EXPRESION -> PARENI, error, PAREND
#line 203 "MiniLang.y"
                          { yyerror("expresion invalida dentro de parentesis"); }
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 210 "MiniLang.y"

private LectorTokens lector;
private ControlSintactico control;

public Parser(LectorTokens lectorEntrada, ControlSintactico controlEntrada) : base(lectorEntrada)
{
    lector = lectorEntrada;
    control = controlEntrada;
}

public int yylex()
{
    return lector.yylex();
}

public void yyerror(string mensaje)
{
    if (string.IsNullOrWhiteSpace(mensaje))
    {
        mensaje = "error sintactico";
    }

    control.AgregarError(mensaje);
}
#line default
}
}
