// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.2.5.0
// Machine:  LAPTOP-FN2SKSA2
// DateTime: 18/04/2026 10:22:47
// Input file <MiniLang.y - 18/04/2026 10:22:11>

// options: lines

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using StarodubOleg.GPPG.Runtime;

namespace Proyecto1Analizador
{
public enum Tokens {error=2,EOF=3,PRINT=4,PRFLOAT=5,PRCHAR=6,
    PRBOOL=7,PRIF=8,PRELIF=9,PRELSE=10,PRWHILE=11,PRDEF=12,
    PRRETURN=13,PRREAD=14,PRWRITE=15,INT=16,FLOAT=17,CHAR=18,
    BOOL=19,ID=20,OR=21,AND=22,NOT=23,SUM=24,
    RESTA=25,MULTI=26,DIV=27,PORCENTAJE=28,IGUAL=29,IGUALIGUAL=30,
    NOIGUAL=31,MAYORQ=32,MENORQ=33,MAYORIGUAL=34,MENORIGUAL=35,PARENI=36,
    PAREND=37,COMA=38,NEWLINE=39,INDENT=40,DEDENT=41,ERROR=42};

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.2.5.0")]
public partial class Parser: ShiftReduceParser<int, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[95];
  private static State[] states = new State[153];
  private static string[] nonTerms = new string[] {
      "S", "$accept", "LINEAS", "LINEA", "SENTENCIA", "DECLARACION", "ASIGNACION",
      "EXPRESION", "IF", "WHILE", "ENTRADASALIDA", "FUNCION", "TIPO", "DATO",
      "CONDICION", "BLOQUE", "ELIFS", "ELSEP", "ELIF", "PARAMETROS", "BLOQUEFUNCION",
      "PARAMS", "PARAM", "RETURN", "LINEASBLOQUE", "LINEABLOQUE", "SENTENCIABLOQUE",
      "LINEASFUNCION", "LINEAFUNCION", "SENTENCIAFUNCION", "LLAMADA", "ARGUMENTOS",
      "LISTAARGUMENTOS", };

  static Parser() {
    states[0] = new State(-4,new int[]{-1,1,-3,3});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{4,57,5,58,6,59,7,60,20,62,16,46,17,47,18,48,19,49,36,51,23,54,8,67,11,90,14,98,15,102,12,121,39,150,2,151,3,-2},new int[]{-4,4,-5,5,-6,7,-13,8,-7,61,-8,65,-14,45,-31,50,-9,66,-10,118,-11,119,-12,120});
    states[4] = new State(-3);
    states[5] = new State(new int[]{39,6,4,-6,5,-6,6,-6,7,-6,20,-6,16,-6,17,-6,18,-6,19,-6,36,-6,23,-6,8,-6,11,-6,14,-6,15,-6,12,-6,2,-6,3,-6});
    states[6] = new State(-5);
    states[7] = new State(-9);
    states[8] = new State(new int[]{20,9});
    states[9] = new State(new int[]{29,10,39,-24,4,-24,5,-24,6,-24,7,-24,20,-24,16,-24,17,-24,18,-24,19,-24,36,-24,23,-24,8,-24,11,-24,14,-24,15,-24,12,-24,2,-24,3,-24,41,-24,13,-24});
    states[10] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,11,-14,45,-31,50});
    states[11] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-25,4,-25,5,-25,6,-25,7,-25,20,-25,16,-25,17,-25,18,-25,19,-25,36,-25,23,-25,8,-25,11,-25,14,-25,15,-25,12,-25,2,-25,3,-25,41,-25,13,-25});
    states[12] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,13,-14,45,-31,50});
    states[13] = new State(new int[]{21,-82,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-82,4,-82,5,-82,6,-82,7,-82,20,-82,16,-82,17,-82,18,-82,19,-82,36,-82,23,-82,8,-82,11,-82,14,-82,15,-82,12,-82,2,-82,3,-82,41,-82,13,-82,38,-82,37,-82});
    states[14] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,15,-14,45,-31,50});
    states[15] = new State(new int[]{21,-83,22,-83,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-83,4,-83,5,-83,6,-83,7,-83,20,-83,16,-83,17,-83,18,-83,19,-83,36,-83,23,-83,8,-83,11,-83,14,-83,15,-83,12,-83,2,-83,3,-83,41,-83,13,-83,38,-83,37,-83});
    states[16] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,17,-14,45,-31,50});
    states[17] = new State(new int[]{21,-84,22,-84,20,-84,7,-84,6,-84,5,-84,4,-84,39,-84,24,28,25,30,26,32,27,34,28,36,16,-84,17,-84,18,-84,19,-84,36,-84,23,-84,8,-84,11,-84,14,-84,15,-84,12,-84,2,-84,3,-84,41,-84,13,-84,38,-84,37,-84});
    states[18] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,19,-14,45,-31,50});
    states[19] = new State(new int[]{21,-85,22,-85,20,-85,7,-85,6,-85,5,-85,4,-85,39,-85,24,28,25,30,26,32,27,34,28,36,16,-85,17,-85,18,-85,19,-85,36,-85,23,-85,8,-85,11,-85,14,-85,15,-85,12,-85,2,-85,3,-85,41,-85,13,-85,38,-85,37,-85});
    states[20] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,21,-14,45,-31,50});
    states[21] = new State(new int[]{21,-86,22,-86,20,-86,7,-86,6,-86,5,-86,4,-86,39,-86,24,28,25,30,26,32,27,34,28,36,16,-86,17,-86,18,-86,19,-86,36,-86,23,-86,8,-86,11,-86,14,-86,15,-86,12,-86,2,-86,3,-86,41,-86,13,-86,38,-86,37,-86});
    states[22] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,23,-14,45,-31,50});
    states[23] = new State(new int[]{21,-87,22,-87,20,-87,7,-87,6,-87,5,-87,4,-87,39,-87,24,28,25,30,26,32,27,34,28,36,16,-87,17,-87,18,-87,19,-87,36,-87,23,-87,8,-87,11,-87,14,-87,15,-87,12,-87,2,-87,3,-87,41,-87,13,-87,38,-87,37,-87});
    states[24] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,25,-14,45,-31,50});
    states[25] = new State(new int[]{21,-88,22,-88,20,-88,7,-88,6,-88,5,-88,4,-88,39,-88,24,28,25,30,26,32,27,34,28,36,16,-88,17,-88,18,-88,19,-88,36,-88,23,-88,8,-88,11,-88,14,-88,15,-88,12,-88,2,-88,3,-88,41,-88,13,-88,38,-88,37,-88});
    states[26] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,27,-14,45,-31,50});
    states[27] = new State(new int[]{21,-89,22,-89,20,-89,7,-89,6,-89,5,-89,4,-89,39,-89,24,28,25,30,26,32,27,34,28,36,16,-89,17,-89,18,-89,19,-89,36,-89,23,-89,8,-89,11,-89,14,-89,15,-89,12,-89,2,-89,3,-89,41,-89,13,-89,38,-89,37,-89});
    states[28] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,29,-14,45,-31,50});
    states[29] = new State(new int[]{21,-90,22,-90,30,-90,31,-90,32,-90,33,-90,34,-90,35,-90,24,-90,25,-90,26,32,27,34,28,36,39,-90,4,-90,5,-90,6,-90,7,-90,20,-90,16,-90,17,-90,18,-90,19,-90,36,-90,23,-90,8,-90,11,-90,14,-90,15,-90,12,-90,2,-90,3,-90,41,-90,13,-90,38,-90,37,-90});
    states[30] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,31,-14,45,-31,50});
    states[31] = new State(new int[]{21,-91,22,-91,30,-91,31,-91,32,-91,33,-91,34,-91,35,-91,24,-91,25,-91,26,32,27,34,28,36,39,-91,4,-91,5,-91,6,-91,7,-91,20,-91,16,-91,17,-91,18,-91,19,-91,36,-91,23,-91,8,-91,11,-91,14,-91,15,-91,12,-91,2,-91,3,-91,41,-91,13,-91,38,-91,37,-91});
    states[32] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,33,-14,45,-31,50});
    states[33] = new State(-92);
    states[34] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,35,-14,45,-31,50});
    states[35] = new State(-93);
    states[36] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,37,-14,45,-31,50});
    states[37] = new State(-94);
    states[38] = new State(new int[]{36,39,21,-77,22,-77,30,-77,31,-77,32,-77,33,-77,34,-77,35,-77,24,-77,25,-77,26,-77,27,-77,28,-77,39,-77,4,-77,5,-77,6,-77,7,-77,20,-77,16,-77,17,-77,18,-77,19,-77,23,-77,8,-77,11,-77,14,-77,15,-77,12,-77,2,-77,3,-77,41,-77,13,-77,38,-77,37,-77});
    states[39] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54,37,-73},new int[]{-32,40,-33,42,-8,56,-14,45,-31,50});
    states[40] = new State(new int[]{37,41});
    states[41] = new State(-71);
    states[42] = new State(new int[]{38,43,37,-72});
    states[43] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,44,-14,45,-31,50});
    states[44] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,38,-75,37,-75});
    states[45] = new State(-78);
    states[46] = new State(-20);
    states[47] = new State(-21);
    states[48] = new State(-22);
    states[49] = new State(-23);
    states[50] = new State(-79);
    states[51] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,52,-14,45,-31,50});
    states[52] = new State(new int[]{37,53,21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36}); 
    states[53] = new State(-80);
    states[54] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,55,-14,45,-31,50});
    states[55] = new State(new int[]{21,-81,22,-81,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-81,4,-81,5,-81,6,-81,7,-81,20,-81,16,-81,17,-81,18,-81,19,-81,36,-81,23,-81,8,-81,11,-81,14,-81,15,-81,12,-81,2,-81,3,-81,41,-81,13,-81,38,-81,37,-81});
    states[56] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,38,-74,37,-74});
    states[57] = new State(-16);
    states[58] = new State(-17);
    states[59] = new State(-18);
    states[60] = new State(-19);
    states[61] = new State(-10);
    states[62] = new State(new int[]{29,63,36,39,21,-77,22,-77,30,-77,31,-77,32,-77,33,-77,34,-77,35,-77,24,-77,25,-77,26,-77,27,-77,28,-77,39,-77,4,-77,5,-77,6,-77,7,-77,20,-77,16,-77,17,-77,18,-77,19,-77,23,-77,8,-77,11,-77,14,-77,15,-77,12,-77,2,-77,3,-77,41,-77,13,-77});
    states[63] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,64,-14,45,-31,50});
    states[64] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-26,4,-26,5,-26,6,-26,7,-26,20,-26,16,-26,17,-26,18,-26,19,-26,36,-26,23,-26,8,-26,11,-26,14,-26,15,-26,12,-26,2,-26,3,-26,41,-26,13,-26});
    states[65] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-11,4,-11,5,-11,6,-11,7,-11,20,-11,16,-11,17,-11,18,-11,19,-11,36,-11,23,-11,8,-11,11,-11,14,-11,15,-11,12,-11,2,-11,3,-11});     
    states[66] = new State(-12);
    states[67] = new State(new int[]{36,68});
    states[68] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-15,69,-8,96,-14,45,-31,50});     
    states[69] = new State(new int[]{37,70});
    states[70] = new State(new int[]{39,71});
    states[71] = new State(new int[]{40,79},new int[]{-16,72});
    states[72] = new State(-29,new int[]{-17,73});
    states[73] = new State(new int[]{10,76,9,112,39,-32,4,-32,5,-32,6,-32,7,-32,20,-32,16,-32,17,-32,18,-32,19,-32,36,-32,23,-32,8,-32,11,-32,14,-32,15,-32,12,-32,2,-32,3,-32,41,-32,13,-32},new int[]{-18,74,-19,75});
    states[74] = new State(-27);
    states[75] = new State(-28);
    states[76] = new State(new int[]{39,77});
    states[77] = new State(new int[]{40,79},new int[]{-16,78});
    states[78] = new State(-31);
    states[79] = new State(-45,new int[]{-25,80});
    states[80] = new State(new int[]{41,81,4,57,5,58,6,59,7,60,20,62,16,46,17,47,18,48,19,49,36,51,23,54,8,67,11,90,14,98,15,102,13,107,39,109,2,110},new int[]{-26,82,-27,83,-6,85,-13,8,-7,86,-8,87,-14,45,-31,50,-9,88,-10,89,-11,97,-24,106});      
    states[81] = new State(-43);
    states[82] = new State(-44);
    states[83] = new State(new int[]{39,84,41,-47,4,-47,5,-47,6,-47,7,-47,20,-47,16,-47,17,-47,18,-47,19,-47,36,-47,23,-47,8,-47,11,-47,14,-47,15,-47,13,-47,2,-47});
    states[84] = new State(-46);
    states[85] = new State(-50);
    states[86] = new State(-51);
    states[87] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-52,41,-52,4,-52,5,-52,6,-52,7,-52,20,-52,16,-52,17,-52,18,-52,19,-52,36,-52,23,-52,8,-52,11,-52,14,-52,15,-52,13,-52,2,-52});    
    states[88] = new State(-53);
    states[89] = new State(-54);
    states[90] = new State(new int[]{36,91});
    states[91] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-15,92,-8,96,-14,45,-31,50});     
    states[92] = new State(new int[]{37,93});
    states[93] = new State(new int[]{39,94});
    states[94] = new State(new int[]{40,79},new int[]{-16,95});
    states[95] = new State(-33);
    states[96] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,37,-76});
    states[97] = new State(-55);
    states[98] = new State(new int[]{36,99});
    states[99] = new State(new int[]{20,100});
    states[100] = new State(new int[]{37,101});
    states[101] = new State(-34);
    states[102] = new State(new int[]{36,103});
    states[103] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,104,-14,45,-31,50});
    states[104] = new State(new int[]{37,105,21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36});
    states[105] = new State(-35);
    states[106] = new State(-56);
    states[107] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-8,108,-14,45,-31,50});
    states[108] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-42,41,-42,4,-42,5,-42,6,-42,7,-42,20,-42,16,-42,17,-42,18,-42,19,-42,36,-42,23,-42,8,-42,11,-42,14,-42,15,-42,13,-42,2,-42});   
    states[109] = new State(-48);
    states[110] = new State(new int[]{39,111});
    states[111] = new State(-49);
    states[112] = new State(new int[]{36,113});
    states[113] = new State(new int[]{20,38,16,46,17,47,18,48,19,49,36,51,23,54},new int[]{-15,114,-8,96,-14,45,-31,50});   
    states[114] = new State(new int[]{37,115});
    states[115] = new State(new int[]{39,116});
    states[116] = new State(new int[]{40,79},new int[]{-16,117});
    states[117] = new State(-30);
    states[118] = new State(-13);
    states[119] = new State(-14);
    states[120] = new State(-15);
    states[121] = new State(new int[]{20,122});
    states[122] = new State(new int[]{36,123});
    states[123] = new State(new int[]{4,57,5,58,6,59,7,60,37,-38},new int[]{-20,124,-22,144,-23,149,-13,147});
    states[124] = new State(new int[]{37,125});
    states[125] = new State(new int[]{39,126});
    states[126] = new State(new int[]{40,128},new int[]{-21,127});
    states[127] = new State(-36);
    states[128] = new State(-59,new int[]{-28,129});
    states[129] = new State(new int[]{41,130,4,57,5,58,6,59,7,60,20,62,16,46,17,47,18,48,19,49,36,51,23,54,8,67,11,90,14,98,15,102,13,107,39,141,2,142},new int[]{-29,131,-30,132,-6,134,-13,8,-7,135,-8,136,-14,45,-31,50,-9,137,-10,138,-11,139,-24,140});
    states[130] = new State(-57);
    states[131] = new State(-58);
    states[132] = new State(new int[]{39,133,41,-61,4,-61,5,-61,6,-61,7,-61,20,-61,16,-61,17,-61,18,-61,19,-61,36,-61,23,-61,8,-61,11,-61,14,-61,15,-61,13,-61,2,-61});
    states[133] = new State(-60);
    states[134] = new State(-64);
    states[135] = new State(-65);
    states[136] = new State(new int[]{21,12,22,14,30,16,31,18,32,20,33,22,34,24,35,26,24,28,25,30,26,32,27,34,28,36,39,-66,41,-66,4,-66,5,-66,6,-66,7,-66,20,-66,16,-66,17,-66,18,-66,19,-66,36,-66,23,-66,8,-66,11,-66,14,-66,15,-66,13,-66,2,-66});   
    states[137] = new State(-67);
    states[138] = new State(-68);
    states[139] = new State(-69);
    states[140] = new State(-70);
    states[141] = new State(-62);
    states[142] = new State(new int[]{39,143});
    states[143] = new State(-63);
    states[144] = new State(new int[]{38,145,37,-37});
    states[145] = new State(new int[]{4,57,5,58,6,59,7,60},new int[]{-23,146,-13,147});
    states[146] = new State(-40);
    states[147] = new State(new int[]{20,148});
    states[148] = new State(-41);
    states[149] = new State(-39);
    states[150] = new State(-7);
    states[151] = new State(new int[]{39,152});
    states[152] = new State(-8);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,3});
    rules[2] = new Rule(-1, new int[]{-3});
    rules[3] = new Rule(-3, new int[]{-3,-4});
    rules[4] = new Rule(-3, new int[]{});
    rules[5] = new Rule(-4, new int[]{-5,39});
    rules[6] = new Rule(-4, new int[]{-5});
    rules[7] = new Rule(-4, new int[]{39});
    rules[8] = new Rule(-4, new int[]{2,39});
    rules[9] = new Rule(-5, new int[]{-6});
    rules[10] = new Rule(-5, new int[]{-7});
    rules[11] = new Rule(-5, new int[]{-8});
    rules[12] = new Rule(-5, new int[]{-9});
    rules[13] = new Rule(-5, new int[]{-10});
    rules[14] = new Rule(-5, new int[]{-11});
    rules[15] = new Rule(-5, new int[]{-12});
    rules[16] = new Rule(-13, new int[]{4});
    rules[17] = new Rule(-13, new int[]{5});
    rules[18] = new Rule(-13, new int[]{6});
    rules[19] = new Rule(-13, new int[]{7});
    rules[20] = new Rule(-14, new int[]{16});
    rules[21] = new Rule(-14, new int[]{17});
    rules[22] = new Rule(-14, new int[]{18});
    rules[23] = new Rule(-14, new int[]{19});
    rules[24] = new Rule(-6, new int[]{-13,20});
    rules[25] = new Rule(-6, new int[]{-13,20,29,-8});
    rules[26] = new Rule(-7, new int[]{20,29,-8});
    rules[27] = new Rule(-9, new int[]{8,36,-15,37,39,-16,-17,-18});
    rules[28] = new Rule(-17, new int[]{-17,-19});
    rules[29] = new Rule(-17, new int[]{});
    rules[30] = new Rule(-19, new int[]{9,36,-15,37,39,-16});
    rules[31] = new Rule(-18, new int[]{10,39,-16});
    rules[32] = new Rule(-18, new int[]{});
    rules[33] = new Rule(-10, new int[]{11,36,-15,37,39,-16});
    rules[34] = new Rule(-11, new int[]{14,36,20,37});
    rules[35] = new Rule(-11, new int[]{15,36,-8,37});
    rules[36] = new Rule(-12, new int[]{12,20,36,-20,37,39,-21});
    rules[37] = new Rule(-20, new int[]{-22});
    rules[38] = new Rule(-20, new int[]{});
    rules[39] = new Rule(-22, new int[]{-23});
    rules[40] = new Rule(-22, new int[]{-22,38,-23});
    rules[41] = new Rule(-23, new int[]{-13,20});
    rules[42] = new Rule(-24, new int[]{13,-8});
    rules[43] = new Rule(-16, new int[]{40,-25,41});
    rules[44] = new Rule(-25, new int[]{-25,-26});
    rules[45] = new Rule(-25, new int[]{});
    rules[46] = new Rule(-26, new int[]{-27,39});
    rules[47] = new Rule(-26, new int[]{-27});
    rules[48] = new Rule(-26, new int[]{39});
    rules[49] = new Rule(-26, new int[]{2,39});
    rules[50] = new Rule(-27, new int[]{-6});
    rules[51] = new Rule(-27, new int[]{-7});
    rules[52] = new Rule(-27, new int[]{-8});
    rules[53] = new Rule(-27, new int[]{-9});
    rules[54] = new Rule(-27, new int[]{-10});
    rules[55] = new Rule(-27, new int[]{-11});
    rules[56] = new Rule(-27, new int[]{-24});
    rules[57] = new Rule(-21, new int[]{40,-28,41});
    rules[58] = new Rule(-28, new int[]{-28,-29});
    rules[59] = new Rule(-28, new int[]{});
    rules[60] = new Rule(-29, new int[]{-30,39});
    rules[61] = new Rule(-29, new int[]{-30});
    rules[62] = new Rule(-29, new int[]{39});
    rules[63] = new Rule(-29, new int[]{2,39});
    rules[64] = new Rule(-30, new int[]{-6});
    rules[65] = new Rule(-30, new int[]{-7});
    rules[66] = new Rule(-30, new int[]{-8});
    rules[67] = new Rule(-30, new int[]{-9});
    rules[68] = new Rule(-30, new int[]{-10});
    rules[69] = new Rule(-30, new int[]{-11});
    rules[70] = new Rule(-30, new int[]{-24});
    rules[71] = new Rule(-31, new int[]{20,36,-32,37});
    rules[72] = new Rule(-32, new int[]{-33});
    rules[73] = new Rule(-32, new int[]{});
    rules[74] = new Rule(-33, new int[]{-8});
    rules[75] = new Rule(-33, new int[]{-33,38,-8});
    rules[76] = new Rule(-15, new int[]{-8});
    rules[77] = new Rule(-8, new int[]{20});
    rules[78] = new Rule(-8, new int[]{-14});
    rules[79] = new Rule(-8, new int[]{-31});
    rules[80] = new Rule(-8, new int[]{36,-8,37});
    rules[81] = new Rule(-8, new int[]{23,-8});
    rules[82] = new Rule(-8, new int[]{-8,21,-8});
    rules[83] = new Rule(-8, new int[]{-8,22,-8});
    rules[84] = new Rule(-8, new int[]{-8,30,-8});
    rules[85] = new Rule(-8, new int[]{-8,31,-8});
    rules[86] = new Rule(-8, new int[]{-8,32,-8});
    rules[87] = new Rule(-8, new int[]{-8,33,-8});
    rules[88] = new Rule(-8, new int[]{-8,34,-8});
    rules[89] = new Rule(-8, new int[]{-8,35,-8});
    rules[90] = new Rule(-8, new int[]{-8,24,-8});
    rules[91] = new Rule(-8, new int[]{-8,25,-8});
    rules[92] = new Rule(-8, new int[]{-8,26,-8});
    rules[93] = new Rule(-8, new int[]{-8,27,-8});
    rules[94] = new Rule(-8, new int[]{-8,28,-8});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }
}

#line 216 "MiniLang.y"

public partial class Parser
{
    private LectorTokens lector;
    private ControlSintactico control;

    public Parser(LectorTokens lectorEntrada, ControlSintactico controlEntrada) : base(lectorEntrada)
    {
        lector = lectorEntrada;
        control = controlEntrada;
    }

    public int yylex()
    {
        return lector.yylex();
    }

    public void yyerror(string mensaje)
    {
        control.AgregarError("error sintactico");
    }
}
#line default
}
